version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongo:27017/
      - MQTT_BROKER=mqtt://mosquitto:1883
    depends_on:
      - mongo
      - mosquitto
    volumes:
      - ./src:/app/src
    networks:
      - sound-monitoring-network

  mongo:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_DATABASE=sound_monitoring
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - sound-monitoring-network

  mosquitto:
    image: eclipse-mosquitto:2.0
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - sound-monitoring-network

volumes:
  mongo-data:

networks:
  sound-monitoring-network:
    driver: bridge
